openapi: 3.0.4
info:
  title: Article Ideas Generator
  description: Article Ideas is a simple tool for generating article ideas. It returns a list of article ideas.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/articleideas:
    get:
      summary: Generate Ideas
      description: Article Ideas is a simple tool for generating article ideas. It returns a list of article ideas.
      operationId: articleideas
      parameters:
      - name: topic
        in: query
        schema:
          type: string
        required: true
        description: The topic for which you want to generate article ideas (up to 50 characters)
        example: software and technology
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  topic: software and technology
                  topicIdeas: 3
                  topics:
                  - 'The Future of AI: How Artificial Intelligence is Revolutionizing Software Development'
                  - 'Breaking Barriers: Exploring the Latest Innovations in Cybersecurity Technology'
                  - 'Beyond the Metaverse: Emerging Trends and Technologies Shaping the Digital Landscape'
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
