name: apiverve_articleideas
description: Article Ideas is a simple tool for generating article ideas. It returns a list of article ideas.
version: 1.1.14
homepage: https://apiverve.com/marketplace/articleideas?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/articleideas-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
